hostname: btd452
is_deployed: true
router_bgp:
  as: '65001'
  router_id: 100.64.200.5
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: LEAF-SPINE
    type: ipv4
    maximum_routes: 12000
    send_community: all
  address_family_ipv4:
    peer_groups:
    - name: LEAF-SPINE
      activate: true
  redistribute_routes:
  - source_protocol: connected
    route_map: rm_subnets
  neighbors:
  - ip_address: 100.64.102.16
    peer_group: LEAF-SPINE
    remote_as: '65001'
    peer: btd555
    description: btd555_Ethernet1/1
  - ip_address: 100.64.102.18
    peer_group: LEAF-SPINE
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet1/1
  - ip_address: 100.64.102.20
    peer_group: LEAF-SPINE
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet2/1
  - ip_address: 100.64.102.22
    peer_group: LEAF-SPINE
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet3/1
static_routes:
- vrf: default
  destination_address_prefix: 10.80.0.0/12
  gateway: 172.28.128.1
- vrf: default
  destination_address_prefix: 172.16.0.0/12
  gateway: 172.28.128.1
- vrf: default
  destination_address_prefix: 10.239.0.0/16
  gateway: 172.28.128.1
- vrf: default
  destination_address_prefix: 10.240.0.0/13
  gateway: 172.28.128.1
service_routing_protocols_model: multi-agent
ip_routing: true
router_multicast:
  ipv4:
    routing: true
daemon_terminattr:
  cvaddrs:
  - 172.28.134.30:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: default
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 4010
    ending: 4090
ip_name_servers:
- ip_address: 172.22.60.20
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$fTv/8ehbz7BW408.$5uaZiXapZq7WazT6BrfDktsjLFM6MIpbnpZp62wEaCLZ6ILbw2WuQ2Z2THkiDQk.IXv2RpUZ13zbHfApT/EO81
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$MUlXuH7QQNH4qejR$m2d./2h0PQd/Ls3V8IwSouMMIxrDMl7cobLtjKpXpAUU7f53RXp92RhKbQ.2fb7wm.TeYFO7f7D4kKmGwWKuC0
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 172.28.137.60/20
  gateway: 172.28.128.1
  type: oob
mac_address_table:
  aging_time: 21600
management_api_http:
  enable_vrfs:
  - name: default
  enable_http: true
  enable_https: true
ethernet_interfaces:
- name: Ethernet1/1
  peer: btd555
  peer_interface: Ethernet1/1
  peer_type: spine
  description: P2P_LINK_TO_BTD555_Ethernet1/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.17/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet2/1
  peer: btd556
  peer_interface: Ethernet1/1
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet1/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.19/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet3/1
  peer: btd556
  peer_interface: Ethernet2/1
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet2/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.21/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet4/1
  peer: btd556
  peer_interface: Ethernet3/1
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet3/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.23/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet6/1
  peer: dc1-LEAF11
  peer_interface: Eth6/1
  peer_type: server
  port_profile: VLAN_LEAF11
  description: connected to ixia
  shutdown: false
  type: switched
  mode: trunk
  vlans: 10-19
  speed: forced 10000full
- name: Ethernet7/1
  peer: dc1-LEAF11
  peer_interface: Eth7/1
  peer_type: server
  port_profile: VLAN_LEAF11
  description: connected to ixia
  shutdown: false
  type: switched
  mode: trunk
  vlans: 10-19
  speed: forced 10000full
- name: Ethernet9/1
  peer: dc1-LEAF11
  peer_interface: Eth9/1
  peer_type: server
  port_profile: VLAN_LEAF11
  description: connected to ixia
  shutdown: false
  type: switched
  mode: trunk
  vlans: 10-19
  speed: forced 25gfull
- name: Ethernet19/1
  peer: dc1-LEAF11
  peer_interface: Eth19/1
  peer_type: server
  port_profile: VLAN_LEAF11
  description: connected to ixia
  shutdown: false
  type: switched
  mode: trunk
  vlans: 10-19
  speed: forced 25gfull
- name: Ethernet8/1
  peer: dc1-LEAF11
  peer_interface: Eth8/1
  peer_type: server
  port_profile: VLAN_LEAF11_scale
  description: connected to ixia
  shutdown: false
  type: switched
  mode: trunk
  vlans: 100-299
  speed: forced 25gfull
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 100.64.200.5/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 100.64.200.0/24 eq 32
- name: prefix_subnets
  sequence_numbers:
  - sequence: 10
    action: permit 100.64.200.0/24 eq 32
  - sequence: 20
    action: permit 100.0.0.0/8 eq 26
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: rm_subnets
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list prefix_subnets
router_pim_sparse_mode:
  ipv4:
    rp_addresses:
    - address: 2.0.0.1
vlans:
- id: 10
  name: vlan_10
  tenant: test
- id: 11
  name: vlan_11
  tenant: test
- id: 12
  name: vlan_12
  tenant: test
- id: 13
  name: vlan_13
  tenant: test
- id: 14
  name: vlan_14
  tenant: test
- id: 15
  name: vlan_15
  tenant: test
- id: 16
  name: vlan_16
  tenant: test
- id: 17
  name: vlan_17
  tenant: test
- id: 18
  name: vlan_18
  tenant: test
- id: 19
  name: vlan_19
  tenant: test
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:00:01:01:02:02
vlan_interfaces:
- name: Vlan10
  tenant: test
  description: vlan_10
  shutdown: false
  ip_address: 100.0.10.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan11
  tenant: test
  description: vlan_11
  shutdown: false
  ip_address: 100.0.11.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan12
  tenant: test
  description: vlan_12
  shutdown: false
  ip_address: 100.0.12.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan13
  tenant: test
  description: vlan_13
  shutdown: false
  ip_address: 100.0.13.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan14
  tenant: test
  description: vlan_14
  shutdown: false
  ip_address: 100.0.14.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan15
  tenant: test
  description: vlan_15
  shutdown: false
  ip_address: 100.0.15.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan16
  tenant: test
  description: vlan_16
  shutdown: false
  ip_address: 100.0.16.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan17
  tenant: test
  description: vlan_17
  shutdown: false
  ip_address: 100.0.17.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan18
  tenant: test
  description: vlan_18
  shutdown: false
  ip_address: 100.0.18.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan19
  tenant: test
  description: vlan_19
  shutdown: false
  ip_address: 100.0.19.1/26
  mtu: 9000
  pim:
    ipv4:
      sparse_mode: true
metadata:
  platform: default
