hostname: btd555
is_deployed: true
router_bgp:
  as: '65001'
  router_id: 1.0.0.1
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  neighbors:
  - ip_address: 100.64.102.17
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd452
    description: btd452_Ethernet14/1
  - ip_address: 100.64.102.25
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btp351
    description: btp351_Ethernet14/1
  - ip_address: 100.64.102.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd558
    description: btd558_Ethernet14/1
  - ip_address: 100.64.102.9
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd453
    description: btd453_Ethernet14/1
service_routing_protocols_model: multi-agent
ip_routing: true
router_multicast:
  ipv4:
    routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 172.28.138.46/20
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet14/1
  peer: btd452
  peer_interface: Ethernet14/1
  peer_type: l3leaf
  description: P2P_LINK_TO_BTD452_Ethernet14/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.16/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet14/5
  peer: btp351
  peer_interface: Ethernet14/1
  peer_type: l3leaf
  description: P2P_LINK_TO_BTP351_Ethernet14/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.24/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet15/1
  peer: btd558
  peer_interface: Ethernet14/1
  peer_type: l3leaf
  description: P2P_LINK_TO_BTD558_Ethernet14/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.0/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet15/5
  peer: btd453
  peer_interface: Ethernet14/1
  peer_type: l3leaf
  description: P2P_LINK_TO_BTD453_Ethernet14/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.8/31
  pim:
    ipv4:
      sparse_mode: true
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 1.0.0.1/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 1.0.0.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_pim_sparse_mode:
  ipv4:
    rp_addresses:
    - address: 2.0.0.1
metadata:
  platform: default
