hostname: btd558
is_deployed: true
router_bgp:
  as: '65001'
  router_id: 100.64.200.3
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65001'
    next_hop_self: true
    description: btd453
    maximum_routes: 12000
    send_community: all
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
  neighbors:
  - ip_address: 10.2.5.1
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: btd453
    description: btd453
  - ip_address: 100.64.102.0
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd555
    description: btd555_Ethernet15/1
  - ip_address: 100.64.102.2
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet20/1
  - ip_address: 100.64.102.4
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet21/1
  - ip_address: 100.64.102.6
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet20/5
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
service_routing_protocols_model: multi-agent
ip_routing: true
router_multicast:
  ipv4:
    routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: 4093-4094
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 172.28.138.14/20
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
vlans:
- id: 4093
  tenant: system
  name: LEAF_PEER_L3
  trunk_groups:
  - LEAF_PEER_L3
- id: 4094
  tenant: system
  name: MLAG_PEER
  trunk_groups:
  - MLAG
- id: 30
  name: vlan_30
  tenant: test
vlan_interfaces:
- name: Vlan4093
  description: MLAG_PEER_L3_PEERING
  shutdown: false
  mtu: 9214
  ip_address: 10.2.5.0/31
  pim:
    ipv4:
      sparse_mode: true
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  no_autostate: true
  mtu: 9214
  ip_address: 10.1.5.0/31
- name: Vlan30
  tenant: test
  description: vlan_30
  shutdown: false
  ip_address: 100.0.30.2/26
  mtu: 9000
  ip_virtual_router_addresses:
  - 100.0.30.2
  pim:
    ipv4:
      sparse_mode: true
port_channel_interfaces:
- name: Port-Channel61
  description: MLAG_PEER_btd453_Po61
  type: switched
  shutdown: false
  mode: trunk
  trunk_groups:
  - LEAF_PEER_L3
  - MLAG
ethernet_interfaces:
- name: Ethernet6/1
  peer: btd453
  peer_interface: Ethernet6/1
  peer_type: mlag_peer
  description: MLAG_PEER_btd453_Ethernet6/1
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 61
    mode: active
- name: Ethernet7/1
  peer: btd453
  peer_interface: Ethernet7/1
  peer_type: mlag_peer
  description: MLAG_PEER_btd453_Ethernet7/1
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 61
    mode: active
- name: Ethernet14/1
  peer: btd555
  peer_interface: Ethernet15/1
  peer_type: spine
  description: P2P_LINK_TO_BTD555_Ethernet15/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.1/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet15/1
  peer: btd556
  peer_interface: Ethernet20/1
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet20/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.3/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet16/1
  peer: btd556
  peer_interface: Ethernet21/1
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet21/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.5/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet17/1
  peer: btd556
  peer_interface: Ethernet20/5
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet20/5
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.7/31
  pim:
    ipv4:
      sparse_mode: true
mlag_configuration:
  domain_id: STORAGE-LEAFs
  local_interface: Vlan4094
  peer_address: 10.1.5.1
  peer_link: Port-Channel61
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - origin incomplete
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  - sequence: 40
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-PIM-RP
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 100.64.200.3/32
- name: Loopback1
  description: PIM RP
  ip_address: 2.0.0.1/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 100.64.200.0/24 eq 32
- name: PL-LOOPBACKS-PIM-RP
  sequence_numbers:
  - sequence: 10
    action: permit 2.0.0.1/32
router_msdp:
  originator_id_local_interface: Loopback0
  peers:
  - ipv4_address: 100.64.200.4
    local_interface: Loopback0
    description: btd453
    mesh_groups:
    - name: ANYCAST-RP
router_pim_sparse_mode:
  ipv4:
    rp_addresses:
    - address: 2.0.0.1
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:dc:00:00:00:01
metadata:
  platform: default
