hostname: btp351
is_deployed: true
router_bgp:
  as: '65001'
  router_id: 100.64.200.6
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  neighbors:
  - ip_address: 100.64.102.24
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd555
    description: btd555_Ethernet14/5
  - ip_address: 100.64.102.26
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet18/5
  - ip_address: 100.64.102.28
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet19/1
  - ip_address: 100.64.102.30
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: btd556
    description: btd556_Ethernet19/5
service_routing_protocols_model: multi-agent
ip_routing: true
router_multicast:
  ipv4:
    routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 172.28.138.18/20
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet14/1
  peer: btd555
  peer_interface: Ethernet14/5
  peer_type: spine
  description: P2P_LINK_TO_BTD555_Ethernet14/5
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.25/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet15/1
  peer: btd556
  peer_interface: Ethernet18/5
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet18/5
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.27/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet16/1
  peer: btd556
  peer_interface: Ethernet19/1
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet19/1
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.29/31
  pim:
    ipv4:
      sparse_mode: true
- name: Ethernet17/1
  peer: btd556
  peer_interface: Ethernet19/5
  peer_type: spine
  description: P2P_LINK_TO_BTD556_Ethernet19/5
  shutdown: false
  mtu: 9214
  type: routed
  ip_address: 100.64.102.31/31
  pim:
    ipv4:
      sparse_mode: true
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 100.64.200.6/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 100.64.200.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_pim_sparse_mode:
  ipv4:
    rp_addresses:
    - address: 2.0.0.1
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:dc:00:00:00:01
metadata:
  platform: default
