---

port_profiles:
  PO100:
    mode: trunk
    vlans: "30-39"
    port_channel:
            mode: active
  VLAN_LEAF11:
    mode: trunk
    vlans: "10-19"
  VLAN_LEAF21:
    mode: trunk
    vlans: "20-29" 

servers:
  - name: dc1-Storage-Po100
    rack: dc1-leaf31-Rack1
    adapters:
    #  - type: nic
      - endpoint_ports: [Eth1/1,Eth2/1]
        switch_ports: [Ethernet5/1,Ethernet5/1]
        switches: [btd558, btd453]
        profile: PO100
        port_channel:
                description: PO100
                mode: active
                       
  - name: dc1-LEAF11
    rack: dc1-LEAF11
    adapters:
    #  - type: nic
      - endpoint_ports: [Eth6/1]
        switch_ports: [Ethernet6/1]
        switches: [btd452]
        profile: VLAN_LEAF11 
  - name: dc1-LEAF21
    rack: dc1-LEAF21
    adapters:
    #  - type: nic
      - endpoint_ports: [Eth6/1]
        switch_ports: [Ethernet6/1]
        switches: [btp351]
        profile: VLAN_LEAF21