---
tenants:
  - name: test
    vrfs:
      - name: default
        svis:
          - id: 30
            name: vlan_30
            enabled: true
            mtu: 9000
            ip_address: 100.0.30.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.30.1

          - id: 31
            name: vlan_31
            enabled: true
            mtu: 9000
            ip_address: 100.0.31.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.31.1
            
          - id: 32
            name: vlan_32
            enabled: true
            mtu: 9000
            ip_address: 100.0.32.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.32.1

          - id: 33
            name: vlan_33
            enabled: true
            mtu: 9000
            ip_address: 100.0.33.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.33.1

          - id: 34
            name: vlan_34
            enabled: true
            mtu: 9000
            ip_address: 100.0.34.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.34.1

          - id: 35
            name: vlan_35
            enabled: true
            mtu: 9000
            ip_address: 100.0.35.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.35.1

          - id: 36
            name: vlan_36
            enabled: true
            mtu: 9000
            ip_address: 100.0.36.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.36.1

          - id: 37
            name: vlan_37
            enabled: true
            mtu: 9000
            ip_address: 100.0.37.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.37.1

          - id: 38
            name: vlan_38
            enabled: true
            mtu: 9000
            ip_address: 100.0.38.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.38.1

          - id: 39
            name: vlan_39
            enabled: true
            mtu: 9000
            ip_address: 100.0.39.2/26
            profile: enable_pim
              
            ip_virtual_router_addresses: 
              - 100.0.39.1


svi_profiles:
  - profile: enable_pim
    structured_config:
      pim:
       ipv4:
         sparse_mode: true

custom_structured_configuration_ethernet_interfaces:
   - name: Ethernet6/1
     description: 'connected to ixia'
     speed: 'forced 100gfull'
   - name: Ethernet7/1
     description: 'connected to ixia'
     speed: 'forced 100gfull'
   - name: Ethernet8/1
     description: 'connected to ixia'
     speed: 'forced 10000full'
   - name: Ethernet9/1
     description: 'connected to ixia'
     speed: 'forced 10000full'

#custom_structured_configuration_router_msdp:
#  peers:
#    - ipv4_address: 1.0.0.3
#      local_interface: loopback0
